version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: devexchange_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: devexchangedb
    ports:
      - "55499:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: devexchange_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7
    container_name: devexchange_redis
    ports:
      - "6379:6379"

  authservice:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    container_name: devexchange_authservice
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "5301:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  userprofileservice:
    build:
      context: ./UserProfileService
      dockerfile: Dockerfile
    container_name: devexchange_userprofileservice
    depends_on:
      - postgres
    ports:
      - "5302:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  courseservice:
    build:
      context: ./CourseService
      dockerfile: Dockerfile
    container_name: devexchange_courseservice
    depends_on:
      - postgres
    ports:
      - "5303:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
  offerservice:
    build:
      context: ./OfferService
      dockerfile: Dockerfile
    container_name: devexchange_offerservice
    depends_on:
      - postgres
    ports:
      - "5304:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

 
volumes:
  pgdata:
